"""
This module defines a class InstructLabProvider that interacts with an AI service to improve text based on a given
prompt. It utilizes the requests library to send a POST request to the specified AI_URL with the provided AI_MODEL. The
improve_text method takes a prompt and text as input, combines them, and sends the request to the AI service. It then
processes the response and returns the improved text. If the request fails, an AiError exception is raised.
"""

import requests
from core.env_fetcher import EnvFetcher
from exceptions.exceptions import AiError


class InstructLabProvider:
    """
    This class provides a way to interact with an AI model hosted on a specified URL for improving text generation.

    Attributes:
    - url (str): The URL of the AI model server.
    - model (str): The name or identifier of the AI model used for text generation.
    """

    def __init__(self):
        """
        Initialize the class instance with AI-related environment variables.

        Arguments:
        - self: The class instance itself.

        Side Effects:
        - Sets the 'url' attribute to the value of the environment variable "AI_URL".
        - Sets the 'model' attribute to the value of the environment variable "AI_MODEL".
        """

        self.url = EnvFetcher.get("AI_URL")
        self.model = EnvFetcher.get("AI_MODEL")

    def improve_text(self, prompt: str, text: str) -> str:
        """
        Summary:
        This method sends a POST request to a specified URL with a given prompt and text to improve the text using a
        specific model. It then returns the improved text obtained from the response.

        Arguments:
        - self: The instance of the class.
        - prompt (str): The initial prompt to provide context for improving the text.
        - text (str): The text to be improved based on the provided prompt.

        Return:
        str: The improved text generated by the AI model in response to the provided prompt and text.

        Exceptions:
        - AiError: Raised when the POST request to the URL fails, indicating an issue with the AI service. The
        exception message includes details about the failure, such as the status code and response text.
        """

        full_prompt = f"{prompt}\n\n{text}"
        response = requests.post(
            self.url,
            json={
                "model": self.model,
                "prompt": full_prompt,
                "stream": False,
                "options": {"temperature": 0.3},
            },
            timeout=60,
        )
        if response.status_code == 200:
            return response.json().get("response", "").strip()
        raise AiError(
            f"InstructLab request failed: {response.status_code} - {response.text}"
        )
