name: CI

on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master

env:
  AI_PROVIDER: noop
  JIRA_URL: https://issues.redhat.com
  PROJECT_KEY: AAP
  AFFECTS_VERSION: aa-latest
  COMPONENT_NAME: analytics-hcc-service
  PRIORITY: Normal

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install --dev

      - name: Run black (check only)
        run: pipenv run black . --check

      - name: Run flake8 (ignore line length and unused imports)
        run: pipenv run flake8 . --ignore=E501,F401

  test:
    runs-on: ubuntu-latest
    needs: lint

    env:
      JPAT: ${{ secrets.JPAT }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install --dev

      - name: Run tests with coverage
        run: pipenv run coverage run -m pytest

      - name: Report coverage
        run: pipenv run coverage report -m

      - name: Generate HTML report
        run: pipenv run coverage html

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov
