---
name: CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
permissions: write-all

jobs:
  cicd:
    secrets: inherit
    uses: dmzoneill/dmzoneill/.github/workflows/dispatch.yaml@main
    with:
      test-ready: "true" 
      pypi-extension: "true"
      deb-build: "true"
      rpm-build: "true"
      docker-build: "true"
      VALIDATE_JSCPD: "false"
      VALIDATE_PYTHON_MYPY: "false"
      VALIDATE_PYTHON_PYLINT: "false"
      VALIDATE_DOCKERFILE_HADOLINT: "false"
