---
name: CICD

'on':
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions: write-all

jobs:
  cicd:
    secrets: inherit
    uses: dmzoneill/dmzoneill/.github/workflows/dispatch.yaml@main
    with:
      test-ready: "true"
      pypi-extension: "true"
      deb-build: "true"
      rpm-build: "true"
      docker-build: "true"
      VALIDATE_PYTHON_MYPY: "false"
